; deskwarden/installer/deskwarden.iss
;
; Per-user Inno Setup installer for deskwarden. No admin rights / UAC prompt
; required (PrivilegesRequired=lowest, installs under %LOCALAPPDATA%).
;
; Build-time dependency: Inno Setup 6 (ISCC.exe) only. This script has no
; [Code] section at all: it copies two files, offers the autostart checkbox
; and finishes. See installer/README.md for full build instructions.
;
; Build with:
;   iscc deskwarden.iss /DAppVersion=0.1.0
;
#ifndef AppVersion
  #define AppVersion "0.0.0"
#endif

[Setup]
AppId={{63CBCB72-5383-4AE7-AFB7-5EE0530E4630}
AppName=Deskwarden
AppVersion={#AppVersion}
AppPublisher=deskwarden (unofficial, unaffiliated with Bitwarden, Inc.)
DefaultDirName={localappdata}\Deskwarden
DefaultGroupName=Deskwarden
DisableProgramGroupPage=yes
PrivilegesRequired=lowest
; ------------------------------------------------------------------
; Installing over a RUNNING Deskwarden.
;
; Without the three directives below, setup had no idea the app was running:
; it went straight to copying over a deskwarden.exe that Windows had mapped
; as a running image, so the install failed or left a stale binary. The app
; now creates this exact mutex as the first statement of `fn main` and holds
; it for its whole life (src/app_mutex.rs), so Inno's OpenMutex on it finds
; the running copy and shows "please close Deskwarden, then click OK".
;
; The name is AUTHORED IN ONE PLACE, `app_mutex::APP_MUTEX_NAME`, and merely
; copied here because Inno cannot read a Rust constant. It is not kept in
; sync by hand or by hope: the test
; `app_mutex::tests::the_installer_names_the_same_mutex_this_process_creates`
; include_str!s THIS FILE, parses this line, and fails the build if the two
; ever differ. Change it there first.
;
; `Local\` and not `Global\` on purpose: PrivilegesRequired=lowest and
; DefaultDirName={localappdata} above make this a per-user install, so setup
; runs in the same logon session as the app it is replacing. A global mutex
; would additionally let one user's running copy block a different user's
; install of their own private copy.
AppMutex=Local\Deskwarden-63CBCB72-5383-4AE7-AFB7-5EE0530E4630
;
; And setup ASKS rather than force-closing. Inno 6's Restart Manager could
; close the app for us (CloseApplications=yes, which is the default when
; files are found in use), and for this app that is the wrong answer: a
; Restart Manager close is a TerminateProcess, which runs no destructors and
; no exit path. Deskwarden's clean shutdown takes a copied password back off
; the Windows clipboard (clipboard::clear_if_still_ours_for) and every secret
; in the app zeroizes on drop -- so a force-close would leave the user's
; password sitting on their clipboard and their secrets unwiped in freed
; memory, as a side effect of installing an update. The mutex above makes the
; app exit through its own door instead.
;
; What this gives up: there is now NO automatic fallback. If deskwarden.exe
; is locked by something that does not hold the mutex -- most importantly a
; copy of version 0.8.0 or earlier, which predates the mutex entirely -- setup
; will report a file in use rather than quietly closing it. That first upgrade
; still has to be done with the app closed by hand; every one after it prompts.
CloseApplications=no
RestartApplications=no
; ------------------------------------------------------------------
OutputBaseFilename=deskwarden-{#AppVersion}-installer
; Compiled installer lands directly in installer/, matching what
; .github/workflows/release.yml (Task 6) expects to find and publish --
; without this, Inno's default OutputDir ("Output\" relative to this
; script) would put it one level down from where the release workflow
; looks.
OutputDir=.
Compression=lzma2
SolidCompression=yes
; The app's own icon (generated by ../assets/generate-icon.py and embedded
; into deskwarden.exe by build.rs), reused for setup's window/taskbar entry
; and for the Programs-and-Features entry, so the installer, the app, the
; Start Menu shortcut and the uninstall entry all look like the same product.
SetupIconFile=..\assets\deskwarden.ico
UninstallDisplayIcon={app}\deskwarden.exe

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Files]
Source: "..\target\release\deskwarden.exe"; DestDir: "{app}"; Flags: ignoreversion
; The passphrase word list. `src/password_gen.rs` reads it from beside the
; executable ON DEMAND rather than carrying it in the binary, so this line is
; not optional decoration: without it the installed app refuses every
; passphrase while a development build generates them happily, which is a
; defect nobody sees until release. `WORDLIST_FILE` there is the same
; spelling, and `the_installer_ships_the_wordlist_this_module_reads` reads
; THIS FILE to hold the two together so the name cannot drift.
Source: "..\assets\wordlist.txt"; DestDir: "{app}"; Flags: ignoreversion

[Icons]
Name: "{group}\Deskwarden"; Filename: "{app}\deskwarden.exe"

[Registry]
; HKCU, not HKLM: this is a per-user install with no admin rights, and
; autostart should only apply to the user who installed it. Uninstall
; removes this value automatically via uninsdeletevalue.
;
; `--autostart` is how the app tells a LOGIN start from a DOUBLE-CLICK. The
; owner: "if user launched it - it should show up (not go to tray), if it
; autostart with minimized - it goes to tray." Without an argument the two
; launches are byte-identical -- same exe, same empty command line, same
; working directory -- so there is nothing for the app to decide on. `main`'s
; `launch_intent` reads it; `AUTOSTART_FLAG` there is the same spelling and
; `the_installers_run_entry_passes_the_flag_the_app_reads` holds the two
; together by reading THIS FILE, so the spelling cannot drift.
;
; **Existing installs do not have it, and that is handled by the app rather
; than here.** This line only runs when the `autostart` task is selected, and
; a self-update deliberately passes /MERGETASKS=!autostart (see [Tasks]
; below), so an upgrade never rewrites a Run value that is already there. A
; user who does not reinstall keeps a bare `deskwarden.exe` indefinitely.
; `launch_intent` therefore reads a missing flag as a USER launch: that is
; what those installs do today, so nothing about them changes, and of the two
; ways to be wrong -- showing a window nobody asked for, or silently going to
; the tray when somebody double-clicked -- only the first is recoverable by
; the user. See `launch_intent`'s own doc for the whole argument.
Root: HKCU; Subkey: "Software\Microsoft\Windows\CurrentVersion\Run"; ValueType: string; ValueName: "Deskwarden"; ValueData: """{app}\deskwarden.exe"" --autostart"; Flags: uninsdeletevalue; Tasks: autostart

[Tasks]
; No `checkedonce`: this task is checked by default on EVERY interactive
; install, not only the first. `checkedonce` limits the checked default to a
; first install, so every upgrade -- including one a user started by hand --
; offered the box already cleared, which contradicted README's "on by
; default, opt-out checkbox" for everyone past their first install.
;
; This is only safe because the self-update passes /MERGETASKS=!autostart
; (updater.rs::launch_installer). A silent update applies the DEFAULT task
; set, so without that flag this line would silently write the Run key back
; for a user who had deliberately cleared it -- an unattended change to a
; system setting, which is worse than the wrong default it fixes. The two
; belong together; changing either alone reintroduces one of the bugs.
Name: "autostart"; Description: "Start Deskwarden automatically when you sign in"

[Run]
; Relaunch Deskwarden once setup finishes. Required by the design spec's
; Auto-update section ("with the installer configured to relaunch the app
; after completing"), and load-bearing for the self-update path: updater.rs's
; apply_update launches this installer and the running app then exits, so
; without this the user clicks "Update available" and Deskwarden simply
; disappears until the next sign-in -- or forever, if they declined the
; autostart task.
;
; `postinstall` runs the entry after setup completes in *both* interactive
; and /VERYSILENT modes. `skipifsilent` is deliberately NOT used: the update
; path is precisely the silent one, and it is the case that most needs the
; relaunch. `nowait` because Deskwarden is a long-lived tray app -- setup
; must not sit waiting for the user to quit it.
Filename: "{app}\deskwarden.exe"; Description: "Start Deskwarden"; Flags: postinstall nowait

; **No [Code] section, deliberately.**
;
; This installer copies an app and finishes. It does not fetch, verify, or
; make a wizard page out of anybody else's binary, and it starts no external
; process of any kind.
;
; What used to be here -- a wizard page, a helper script, a signature check
; and four dialogs, all for a dependency that only some accounts need and
; that ran before the user had chosen a server -- is recorded in
; installer/README.md under "What this installer no longer does", together
; with the two findings from it that are still live. The app acquires that
; dependency itself now, at the moment a server is chosen that requires it:
; see src/bw_acquire.rs.
;
; Three tests in src/main.rs hold this file to it:
; `the_installer_says_nothing_about_the_bitwarden_cli`,
; `the_installer_shells_out_to_nothing`, and
; `the_bootstrap_script_is_not_in_the_tree`. They are text scans, so a
; MENTION in a comment here reads exactly like a call -- which is why the
; history lives in the README rather than in this file.
;
; **Uninstall still deliberately leaves what it installed behind.** That
; reasoning is unchanged and has moved to the module that now writes it: see
; src/bw_acquire.rs's module docs. Only deskwarden's own tracked files and
; the autostart registry value (uninsdeletevalue, above) are removed.