; deskwarden/installer/deskwarden.iss
;
; Per-user Inno Setup installer for deskwarden. No admin rights / UAC prompt
; required (PrivilegesRequired=lowest, installs under %LOCALAPPDATA%).
;
; Build-time dependency: Inno Setup 6 (ISCC.exe) only. Unlike an earlier
; draft of this script, this version does NOT use the Inno Download Plugin
; (idp.iss) -- see the [Code] section comment on InstallBwCliIfMissing for
; why. See installer/README.md for full build instructions.
;
; Build with:
;   iscc deskwarden.iss /DAppVersion=0.1.0
;
#ifndef AppVersion
  #define AppVersion "0.0.0"
#endif

[Setup]
AppId={{63CBCB72-5383-4AE7-AFB7-5EE0530E4630}
AppName=Deskwarden
AppVersion={#AppVersion}
AppPublisher=deskwarden (unofficial, unaffiliated with Bitwarden, Inc.)
DefaultDirName={localappdata}\Deskwarden
DefaultGroupName=Deskwarden
DisableProgramGroupPage=yes
PrivilegesRequired=lowest
; ------------------------------------------------------------------
; Installing over a RUNNING Deskwarden.
;
; Without the three directives below, setup had no idea the app was running:
; it went straight to copying over a deskwarden.exe that Windows had mapped
; as a running image, so the install failed or left a stale binary. The app
; now creates this exact mutex as the first statement of `fn main` and holds
; it for its whole life (src/app_mutex.rs), so Inno's OpenMutex on it finds
; the running copy and shows "please close Deskwarden, then click OK".
;
; The name is AUTHORED IN ONE PLACE, `app_mutex::APP_MUTEX_NAME`, and merely
; copied here because Inno cannot read a Rust constant. It is not kept in
; sync by hand or by hope: the test
; `app_mutex::tests::the_installer_names_the_same_mutex_this_process_creates`
; include_str!s THIS FILE, parses this line, and fails the build if the two
; ever differ. Change it there first.
;
; `Local\` and not `Global\` on purpose: PrivilegesRequired=lowest and
; DefaultDirName={localappdata} above make this a per-user install, so setup
; runs in the same logon session as the app it is replacing. A global mutex
; would additionally let one user's running copy block a different user's
; install of their own private copy.
AppMutex=Local\Deskwarden-63CBCB72-5383-4AE7-AFB7-5EE0530E4630
;
; And setup ASKS rather than force-closing. Inno 6's Restart Manager could
; close the app for us (CloseApplications=yes, which is the default when
; files are found in use), and for this app that is the wrong answer: a
; Restart Manager close is a TerminateProcess, which runs no destructors and
; no exit path. Deskwarden's clean shutdown takes a copied password back off
; the Windows clipboard (clipboard::clear_if_still_ours_for) and every secret
; in the app zeroizes on drop -- so a force-close would leave the user's
; password sitting on their clipboard and their secrets unwiped in freed
; memory, as a side effect of installing an update. The mutex above makes the
; app exit through its own door instead.
;
; What this gives up: there is now NO automatic fallback. If deskwarden.exe
; is locked by something that does not hold the mutex -- most importantly a
; copy of version 0.8.0 or earlier, which predates the mutex entirely -- setup
; will report a file in use rather than quietly closing it. That first upgrade
; still has to be done with the app closed by hand; every one after it prompts.
CloseApplications=no
RestartApplications=no
; ------------------------------------------------------------------
OutputBaseFilename=deskwarden-{#AppVersion}-installer
; Compiled installer lands directly in installer/, matching what
; .github/workflows/release.yml (Task 6) expects to find and publish --
; without this, Inno's default OutputDir ("Output\" relative to this
; script) would put it one level down from where the release workflow
; looks.
OutputDir=.
Compression=lzma2
SolidCompression=yes
; The app's own icon (generated by ../assets/generate-icon.py and embedded
; into deskwarden.exe by build.rs), reused for setup's window/taskbar entry
; and for the Programs-and-Features entry, so the installer, the app, the
; Start Menu shortcut and the uninstall entry all look like the same product.
SetupIconFile=..\assets\deskwarden.ico
UninstallDisplayIcon={app}\deskwarden.exe

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Files]
Source: "..\target\release\deskwarden.exe"; DestDir: "{app}"; Flags: ignoreversion
; Helper script for the bw-CLI bootstrap step below. `dontcopy` means it's
; bundled into the installer payload but not installed onto the user's
; system as an app file; it's pulled out on demand via
; ExtractTemporaryFile and run once, then left in {tmp} for Windows to
; clean up.
Source: "bootstrap-bw.ps1"; DestDir: "{tmp}"; Flags: dontcopy

[Icons]
Name: "{group}\Deskwarden"; Filename: "{app}\deskwarden.exe"

[Registry]
; HKCU, not HKLM: this is a per-user install with no admin rights, and
; autostart should only apply to the user who installed it. Uninstall
; removes this value automatically via uninsdeletevalue.
;
; `--autostart` is how the app tells a LOGIN start from a DOUBLE-CLICK. The
; owner: "if user launched it - it should show up (not go to tray), if it
; autostart with minimized - it goes to tray." Without an argument the two
; launches are byte-identical -- same exe, same empty command line, same
; working directory -- so there is nothing for the app to decide on. `main`'s
; `launch_intent` reads it; `AUTOSTART_FLAG` there is the same spelling and
; `the_installers_run_entry_passes_the_flag_the_app_reads` holds the two
; together by reading THIS FILE, so the spelling cannot drift.
;
; **Existing installs do not have it, and that is handled by the app rather
; than here.** This line only runs when the `autostart` task is selected, and
; a self-update deliberately passes /MERGETASKS=!autostart (see [Tasks]
; below), so an upgrade never rewrites a Run value that is already there. A
; user who does not reinstall keeps a bare `deskwarden.exe` indefinitely.
; `launch_intent` therefore reads a missing flag as a USER launch: that is
; what those installs do today, so nothing about them changes, and of the two
; ways to be wrong -- showing a window nobody asked for, or silently going to
; the tray when somebody double-clicked -- only the first is recoverable by
; the user. See `launch_intent`'s own doc for the whole argument.
Root: HKCU; Subkey: "Software\Microsoft\Windows\CurrentVersion\Run"; ValueType: string; ValueName: "Deskwarden"; ValueData: """{app}\deskwarden.exe"" --autostart"; Flags: uninsdeletevalue; Tasks: autostart

[Tasks]
; No `checkedonce`: this task is checked by default on EVERY interactive
; install, not only the first. `checkedonce` limits the checked default to a
; first install, so every upgrade -- including one a user started by hand --
; offered the box already cleared, which contradicted README's "on by
; default, opt-out checkbox" for everyone past their first install.
;
; This is only safe because the self-update passes /MERGETASKS=!autostart
; (updater.rs::launch_installer). A silent update applies the DEFAULT task
; set, so without that flag this line would silently write the Run key back
; for a user who had deliberately cleared it -- an unattended change to a
; system setting, which is worse than the wrong default it fixes. The two
; belong together; changing either alone reintroduces one of the bugs.
Name: "autostart"; Description: "Start Deskwarden automatically when you sign in"

[Run]
; Relaunch Deskwarden once setup finishes. Required by the design spec's
; Auto-update section ("with the installer configured to relaunch the app
; after completing"), and load-bearing for the self-update path: updater.rs's
; apply_update launches this installer and the running app then exits, so
; without this the user clicks "Update available" and Deskwarden simply
; disappears until the next sign-in -- or forever, if they declined the
; autostart task.
;
; `postinstall` runs the entry after setup completes in *both* interactive
; and /VERYSILENT modes. `skipifsilent` is deliberately NOT used: the update
; path is precisely the silent one, and it is the case that most needs the
; relaunch. `nowait` because Deskwarden is a long-lived tray app -- setup
; must not sit waiting for the user to quit it.
Filename: "{app}\deskwarden.exe"; Description: "Start Deskwarden"; Flags: postinstall nowait

[Code]
{ Runs bootstrap-bw.ps1 (see that file for full detail) to ensure bw.exe is
  available, downloading it from Bitwarden's own GitHub releases and
  verifying its Authenticode signature first if it's missing.

  This step shells out to PowerShell rather than using the Inno Download
  Plugin (idp.iss) that an earlier draft of this script referenced. Reasons:

  1. bitwarden/clients (the real, verified repo -- confirmed 2026-07-28
     against https://api.github.com/repos/bitwarden/clients/releases) is a
     monorepo publishing releases for multiple products (cli, desktop,
     browser, web) interleaved by date. GitHub's generic "latest release"
     for the repo is NOT reliably the CLI's latest release -- resolving the
     right one requires filtering the releases list by tag prefix
     ("cli-v*"), which means parsing JSON. Inno's Pascal Script has no JSON
     support and idpDownloadFile alone can't do this resolution; PowerShell
     (Invoke-RestMethod) can, in a handful of readable lines.
  2. This project's own signature-verification code (src/signature.rs)
     already shells out to PowerShell's Get-AuthenticodeSignature rather
     than binding WinVerifyTrust directly, specifically to avoid getting
     security-critical FFI wrong. Doing the same here keeps the bw-CLI
     bootstrap step's verification logic consistent with that choice
     instead of introducing a second, different verification mechanism.
  3. It avoids adding idp.iss as a build-time dependency that Task 6's CI
     workflow (choco install innosetup only installs Inno Setup itself, not
     the plugin) would otherwise need an extra step to fetch.
}
{ Copying deskwarden.exe itself (the [Files] section) already gets a visible
  progress page from Inno's own wizard for a normal interactive install --
  nothing custom is needed for that stage. The two stages below (the
  compatibility check and the CLI bootstrap) are the ones that used to run
  with SW_HIDE and zero visible feedback, which is what ProgressPage exists
  to fix.

  Gated on `not WizardSilent()` throughout: updater.rs's apply_update runs
  this installer with /VERYSILENT for the app's own self-update relaunch,
  and that path must stay fully silent (no windows at all) by design -- the
  same reason the error dialogs below are Suppressible*, not plain, boxes. }
var
  ProgressPage: TOutputProgressWizardPage;

procedure InitializeWizard();
begin
  if not WizardSilent() then
    ProgressPage := CreateOutputProgressPage('Setting up Deskwarden',
      'Please wait while Deskwarden finishes setting up.');
end;

procedure InstallBwCliIfMissing();
var
  ScriptPath: String;
  PowerShellPath: String;
  ResultCode: Integer;
  ExecOk: Boolean;
begin
  { Absolute path rather than the bare 'powershell.exe' this used: setup runs
    out of a user-writable temp directory, and Windows' process-creation
    search order includes the application directory. Same reasoning as
    src/signature.rs resolving powershell.exe absolutely.
    (Note for editors: Pascal brace comments do not nest, so an Inno
    constant written literally in one of these comments would end it early.) }
  PowerShellPath := ExpandConstant('{sys}\WindowsPowerShell\v1.0\powershell.exe');

  if not WizardSilent() then
  begin
    ProgressPage.SetText('Checking compatibility...', 'Confirming PowerShell is available');
    ProgressPage.SetProgress(1, 3);
    ProgressPage.Show();
  end;

  { A real check, not a cosmetic delay: without it, a machine missing this
    (extremely standard, but not guaranteed) component would hit the "could
    not launch PowerShell" failure path below with no more specific cause. }
  if not FileExists(PowerShellPath) then
  begin
    if not WizardSilent() then ProgressPage.Hide();
    SuppressibleMsgBox('Deskwarden could not find PowerShell, which it needs to set up the Bitwarden CLI (bw). ' +
      'Please install it yourself from https://bitwarden.com/help/cli/ and ensure it''s on your PATH.',
      mbInformation, MB_OK, IDOK);
    exit;
  end;

  ExtractTemporaryFile('bootstrap-bw.ps1');
  ScriptPath := ExpandConstant('{tmp}\bootstrap-bw.ps1');

  if not WizardSilent() then
  begin
    ProgressPage.SetText('Installing Bitwarden CLI...',
      'Downloading and verifying the official CLI if it is not already present -- this can take a minute');
    ProgressPage.SetProgress(2, 3);
  end;

  ExecOk := Exec(PowerShellPath,
    Format('-NoProfile -ExecutionPolicy Bypass -File "%s" -InstallDir "%s"', [
      ScriptPath, ExpandConstant('{app}')]),
    '', SW_HIDE, ewWaitUntilTerminated, ResultCode);

  if not WizardSilent() then
  begin
    ProgressPage.SetText('Finishing up...', '');
    ProgressPage.SetProgress(3, 3);
  end;

  { SuppressibleMsgBox, not MsgBox, everywhere below. Inno does NOT
    auto-dismiss plain MsgBox under /SUPPRESSMSGBOXES -- that flag only
    affects the Suppressible* variants. updater.rs's apply_update runs this
    installer with `/VERYSILENT /SUPPRESSMSGBOXES` from a process the user
    never interactively launched, so any of these failure paths (network
    down, GitHub API shape change, signature check failure) would otherwise
    put up an invisible modal dialog and block setup indefinitely. The final
    argument is the answer returned when suppressed; every box here is
    informational with a single OK button, so IDOK is both the only and the
    correct answer. Interactively, these still display exactly as before. }
  if (not ExecOk) then
  begin
    if not WizardSilent() then ProgressPage.Hide();
    SuppressibleMsgBox('Deskwarden could not launch PowerShell to set up the Bitwarden CLI (bw). ' +
      'Please install it yourself from https://bitwarden.com/help/cli/ and ensure it''s on your PATH.',
      mbInformation, MB_OK, IDOK);
    exit;
  end;

  case ResultCode of
    0: ; { success: already present, or freshly installed and verified }
    2: SuppressibleMsgBox('The Bitwarden CLI download did not pass signature verification, so it was not installed. ' +
        'Please install it yourself from https://bitwarden.com/help/cli/ and ensure it''s on your PATH.',
        mbError, MB_OK, IDOK);
  else
    SuppressibleMsgBox('Deskwarden could not automatically set up the Bitwarden CLI (bw). ' +
      'Please install it yourself from https://bitwarden.com/help/cli/ and ensure it''s on your PATH.',
      mbInformation, MB_OK, IDOK);
  end;

  if not WizardSilent() then ProgressPage.Hide();
end;

procedure CurStepChanged(CurStep: TSetupStep);
begin
  if CurStep = ssPostInstall then
    InstallBwCliIfMissing();
end;

{ Deliberately no CurUninstallStepChanged PATH cleanup here: per the design
  spec's Installer section, uninstalling deskwarden intentionally leaves the
  bw CLI (and the PATH entry bootstrap-bw.ps1 added for it) in place, since
  the user may be using bw independently of deskwarden. Only deskwarden's
  own tracked files and the autostart registry value (uninsdeletevalue,
  above) are removed. }
