//! Embeds the Windows resources (currently just the application icon) into
//! the built executable.
//!
//! Without this, `deskwarden.exe` carries no icon resource at all: Explorer,
//! the taskbar, and the Start Menu shortcut the installer creates all fall
//! back to the generic "unknown application" icon. The tray icon is loaded
//! from this same embedded resource at runtime (see `src/tray.rs`), so the
//! icon is defined in exactly one place.
//!
//! `assets/deskwarden.ico` is generated by `assets/generate-icon.py` -- see
//! that script for the design and why it is generated rather than committed
//! as an opaque binary blob.

fn main() {
    println!("cargo:rerun-if-changed=assets/deskwarden.ico");
    println!("cargo:rerun-if-changed=build.rs");

    #[cfg(windows)]
    {
        let mut resource = winresource::WindowsResource::new();
        // Explicit id "1", because `src/tray.rs` loads the icon back by
        // ordinal (`Icon::from_resource(1, ...)`) rather than by name. Left
        // to the default, the id would be an implementation detail of
        // winresource that the runtime lookup would silently depend on.
        resource.set_icon_with_id("assets/deskwarden.ico", "1");

        // Left unset, winresource falls back to Cargo.toml's package `name`
        // ("deskwarden", all lowercase) for these VERSIONINFO fields --
        // that's what Explorer/the taskbar show in places that read the
        // exe's own metadata rather than a window's title text (process
        // properties, some taskbar grouping tooltips). Set explicitly so
        // the app's proper-cased name shows up there too.
        resource.set("ProductName", "Deskwarden");
        resource.set("FileDescription", "Deskwarden");

        // Deliberately a warning rather than a hard failure. Embedding
        // resources needs `rc.exe` (Windows SDK) or `windres`; on a machine
        // that has neither, failing the build would make the whole crate
        // unbuildable over a cosmetic asset. The tray code already handles a
        // missing icon resource by running without an icon, exactly as it did
        // before this existed.
        if let Err(e) = resource.compile() {
            println!("cargo:warning=could not embed the application icon resource: {e}");
        }
    }
}
